### ISSUE TITLE
python example_usage.py --> error

### ISSUE THREAD

**Issue by eunsirbeen** [cachecake404/Trading-View-Data-Monitor#1]
File "C:\apps\anaconda\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9222): Max retries exceeded with url: /json (C
aused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CD7B05C520>: Failed to establish a new c
onnection: [WinError 10061]

**Comment by cachecake404** [comment]
> File "C:\apps\anaconda\lib\site-packages\urllib3\util\retry.py", line 573, in increment
> raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9222): Max retries exceeded with url: /json (C
> aused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CD7B05C520>: Failed to establish a new c
> onnection: [WinError 10061]

This is an error you get when you do not open chrome with the remote debugging setting enabled.

I have updated the documentation and uploaded a short 4 min video to demonstrate how to quickly set things up.
https://www.youtube.com/watch?v=Xouxc_Ntjfo
